### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mohsinulhaq** [asif-ir/request-throttler-express#1]
Instead of rate limiting, my server is now able to handle more requests per second 😣
Please fix.

**Comment by asif-ir** [comment]
Forget the library name and use like this then, sir:

``` javascript
const requestImprover = require('request-throttler-express');
app.use(requestImprover({}));
```

**Comment by mohsinulhaq** [comment]
Thank you sir, you are a genius!
![source](https://user-images.githubusercontent.com/7688231/68083523-7debfd00-fe4f-11e9-98ef-51397895299b.gif)
